from pydantic import BaseModel, Field
from typing import List, Optional
from app.models import Product

class ChatRequest(BaseModel):
    session_id: str
    message: str

class ChatResponse(BaseModel):
    response: str
    
class AgentResponse(BaseModel):
    answer: str = Field(description="Final answer")
    source: str = Field(description="database or general")
    
class NLP_to_Sql(BaseModel):
    sql_query: str = Field(description="SQL query generated by the agent")